repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: "v1.77.1"
  hooks:
    - id: terraform_validate
    - id: terraform_fmt
    - id: terraform_tfsec
    - id: terraform_checkov
    - id: terraform_docs
    - id: infracost_breakdown
      args:
        - --hook-config='.currency == "GBP"'
      verbose: true